services:
  db:
    image: postgres:17-alpine
    container_name: ecti_postgres
    restart: always
    environment:
      POSTGRES_USER: ptea
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: report_auditor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: